### ISSUE TITLE
Create Aporeto Namespace Management Playbook

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#176]
As an operations team member I would like an automation playbook that is used to configure all Aporeto namespace with the desired authentication user & role mapping. This should be stored in Git for versioning and approval workflows. 

A separate playbook is required to facilitate the following: 
- [x] Creation / Removal of Aporeto Namespaces
- [x] Editing of Access Control Lists for each Namespace

**Comment by stewartshea** [comment]
@j-pye  Here is an example where I am creating the openshift namespace in Aporeto; might help when starting to look at the other namespace auth builder playbook: https://github.com/BCDevOps/platform-services/blob/aporeto/security/aporeto/build/ansible/tasks/namespace_preparation.yml

**Comment by stewartshea** [comment]
@j-pye can you update this card with links to your code, etc?

**Comment by tosazuwa** [comment]
@j-pye  whats the status on this please?

**Comment by j-pye** [comment]
Moving back to In Progress while I resolve a github issue. 

 I'm going to try initializing a readme in master first and rebasing my feature branch to get a fresh hash, then try pushing everything again.

**Comment by stewartshea** [comment]
@j-pye any update on this? I see the readme now but that's it.

**Comment by j-pye** [comment]
@stewartshea Working through my last problem right now and updating the readme. 
For the authorization policies, something changed and now for all new policies every user must have their email and the realm set otherwise the api returns a creation/update error. 

It's a little odd though given our policies in /bcgov don't require the realm but maybe that's because they were created before the requirement was introduced.

**Comment by j-pye** [comment]
Branch: https://github.com/bcgov-c/platform-services-secops/tree/namespace-management
Working: 
- Namespace Creation, Update, and Deletion (Including Child Namespace)
- API Authorization Policy Creation, Update, and Deletion

Notes:
- Aporeto returns `{}` for non-existent namespaces as well as the root namespace. 
- Aporeto returns `error 404` when requesting an auth policy that doesn't exist

To-Do:
- Finish README.md
- Explore other ways to update API Auth Policy. 
- Explore checking against a list of Child Namespace instead of Polling individually.
- Update Facts and add Aporeto auth setup instead of assuming the user has set an `APOCTL_TOKEN`, maybe OIDC or AppCred since the playbook will run in a pipeline.

**Comment by stewartshea** [comment]
I've done some testing on this and have moved over management of our namespace and api auth to this playbook. So far so good, it's looking great! Just need a readme update

@j-pye since this is functional, I'd say that your two middle bullets on the last comment are fine for icebox tasks but shouldn't be blockers to closing out this task.

**Comment by j-pye** [comment]
@stewartshea Are all of your changes pushed to the `namespace-management` branch? Let me know and I'll merge the readme and create a PR to merge into master for you to review :)

**Comment by j-pye** [comment]
Created #411  to deal with policies updating every time the playbook runs.

PR : https://github.com/bcgov-c/platform-services-secops/pull/1

After we merge this we should be able to merge the `namespace-management` playbook into master.
@stewartshea

**Comment by stewartshea** [comment]
Merged the readme into namespace management and then into master.
