### ISSUE TITLE
DXC training in Aqua support

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/platform-services#335]
Work required to assist the DXC team to become familiar with the Aqua install and configure playbook and prepare for the production turnover

**Comment by wmhutchison** [comment]
Attended a video meeting with @j-pye last week for a show-and-tell involving the technology. 

Currently awaiting a completed LAB playbook for the things that work correctly, with the aim to test today and provide a final go/no-go on whether or not we can proceed with installing what's working (scan registry only) in PROD this Wednesday.

If the desire is for everything to be working in LAB and not just the registry scanner, then we're likely not in a position to install/use Aqua in PROD until the first week of January (assuming all issues are addressed by then).

**Comment by j-pye** [comment]
Update: 
Continuing in Sprint 8. Deployment to PROD postponed until Jan.

**Comment by wmhutchison** [comment]
@mitovskaol Status update, apologies - I think I posted an earlier update in a ticket that's probably now closed. 

All updates for Aqua playbook last week were published by @j-pye and a cut-off for feature updates made so proper testing could take place (Justin now working on involved work for a version upgrade of Aqua in his own environment).

Un-install in LAB worked, re-install in LAB failed because playbook used a module whose software dependency could not be fulfilled in the DXC server environment. Justin thus started work on containerizing the involved playbook so it will be running in a consistent environment going forward independent of end users' environment.

Justin effective today is working on completing this containerization of the playbook so it can be turned back over to me for re-testing in LAB, and from there, a stable time-frame for when we can run the same in PROD can be derived. Work on this issue has been redirected as a high priority item, only preempted by PROD operational issues that have to be addressed.

If all goes well, am hoping by the end of this week to publish a final "go" for scheduling something for PROD, meaning either a release into PROD environment with the following possibilities:
- release in PROD mid-week (Wednesday Feb 25th, resulting in notification lead time of 3 business days if notification goes out this Friday morning)
- release in PROD the following week (Tuesday February 11th) which would allow for ample notification lead time plus if required, additional internal discussion/approval after DXC gives a "go" for Aqua PROD deployment.

**Comment by tosazuwa** [comment]
Hi @wmhutchison , do you mean Feb 5th? You have Feb 25th listed. Do confirm

**Comment by wmhutchison** [comment]
Technical testing of using the provided playbook has passed regarding installing and un-installing Aqua in LAB. As such a launch date of Wednesday February 12th is what we will aim for since we now need to gather required data to determine the resources that will be allocated to the pods we install in PROD. 

The vendor of the product does not provide any viable method of calculating precise resource requirements - instead they provide example deployments they've tested on their own with specific cluster sizes. 

As such each phase of Aqua we launch in PROD will require resource monitoring to determine if the resources we allocate are adequate as the service is used, and if not, attempt to estimate the final amount required.

For the curious, our Openshift LAB and PROD environments are too dissimilar in capacity and usage to allow LAB resource results to directly drive PROD requirements.
