### ISSUE TITLE
Can't create team with non-license plate namespace name for Sysdig Team

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/platform-services#654]
```
Name:         devex-von-sysdigteam
Namespace:    devex-von-tools
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"ops.gov.bc.ca/v1alpha1","kind":"SysdigTeam","metadata":{"annotations":{},"name":"devex-von-sysdigteam","namespace":"devex-von-tools"},"s...
API Version:  ops.gov.bc.ca/v1alpha1
Kind:         SysdigTeam
Metadata:
  Creation Timestamp:  2020-03-27T13:09:26Z
  Finalizers:
    finalizer.ops.gov.bc.ca
  Generation:        1
  Resource Version:  1686247162
  Self Link:         /apis/ops.gov.bc.ca/v1alpha1/namespaces/devex-von-tools/sysdig-teams/devex-von-sysdigteam
  UID:               2f342c16-702c-11ea-a8b6-005056832285
Spec:
  Team:
    Description:  The Sysdig Team for the VON Namespaces
    Users:
      Name:  wade.barnes@shaw.ca
      Role:  ROLE_TEAM_MANAGER
      Name:  iancostanzo@gmail.com
      Role:  ROLE_TEAM_EDIT
Status:
  Conditions:
    Last Transition Time:  2020-03-27T13:09:26Z
    Message:               Running reconciliation
    Reason:                Running
    Status:                False
    Type:                  Running
    Ansible Result:
      Changed:             0
      Completion:          2020-03-27T13:09:35.857186
      Failures:            1
      Ok:                  0
      Skipped:             0
    Last Transition Time:  2020-03-27T13:09:36Z
    Message:               Object was not created in the Tools namespace. Please place your sysdig-team object there.
    Reason:                Failed
    Status:                True
    Type:                  Failure
Events:                    <none>
```

This is a result of the logic that splits the name by `-` which doesn't work for older non license plate namespaces.

**Comment by WadeBarnes** [comment]
@stewartshea, I should mention one other anomaly that could cause another wrinkle for you ...

`devex-von-tools` is the tools namespace for our `devex-von` AND `devex-von-bc-tob` project sets.  Things were done this way because we started out with the `devex-von` project set, which started as a PoC environment and quickly turned into a project set for our demo and workshop applications.  The `devex-von-bc-tob` project set, consisting of just `dev`, `test`, and `prod`, was provisioned to contain our applications destined for production use since we wanted clear separation between the two use cases.  The applications deployed into each project set are the same, only the deployment configurations and intended use are different, so it did not make sense to duplicate the `tools` project.

**Comment by stewartshea** [comment]
Thanks for the detail @WadeBarnes ; It's very likely that for a use-case like that we will manually manage your team for you. It's not really a pattern that applies to anyone else so I'm not sure it warrants a rewrite of the current logic.

**Comment by WadeBarnes** [comment]
Agreed

**Comment by ShellyXueHan** [comment]
not relavant anymore as in ocp4 all project sets are created with standard naming convention. Please reopen if needed.
