### ISSUE TITLE
CI/CD Tools and Services

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/platform-services#93]
Please provide feedback, below, on which of these services or tools you have used.  
Also please, add any tools you are familiar with that we have missed.

# Pipeline Orchestration Services / SaaS
1. CicleCI - https://circleci.com/
1. Travis - https://travis-ci.org/
1. CodeFresh - https://codefresh.io/
1. Azure DevOps - https://azure.microsoft.com/en-ca/services/devops/
1. Harness - https://harness.io/

# Pipeline Orchestration Tools

1.  Drone - https://drone.io
1.  XL Release/Deploy - https://xebialabs.com/products/xl-release/
1. GitHub Actions - https://github.com/features/actions
1. Jenkins - https://jenkins.io/
1. JenkinsX - https://jenkins-x.io/
1. TeamCity - https://www.jetbrains.com/teamcity/
1. Knative - https://knative.dev/
1. Kubernetes Prow - https://github.com/kubernetes/test-infra/tree/master/prow
1. Huggin - https://github.com/huginn/huginn
1. Kapitan - https://kapitan.dev/
1. Brigade - https://brigade.sh/
1. GitLab - https://about.gitlab.com/product/continuous-integration/
1. Argo - https://github.com/argoproj/argo
1. Kubeless - https://kubeless.io/
1. Gitea - https://gitea.io/en-us/
1. Nomad - https://github.com/hashicorp/nomad
1. GoCD - https://www.gocd.org/
1. Concourse - https://concourse-ci.org/

# Other supporting tools
1. Helm - https://helm.sh/
1. JIRA
1. Confluence
1. wikijs - https://wiki.js.org/
1. documize - https://www.documize.com/

# Dashboard View
https://cncf.ci/

**Comment by jleach** [comment]
I prefer **CircleCI** because it can build for the Apple platform. We may not be able to use it for signing because we don't want to put our keys in a 3rd-party system but at least it can pound out what we need. Android is nice out-of-the-box also but we can easily reproduce this functionality on any Linux based image by installing the SDK/tools we need.

**Comment by wenzowski** [comment]
There's a bunch of new ones in here :) Would love to see artifact repositories and object storage included in this list as they're pretty critical components of a pipeline IMHO. Unless you're intending to limit this list to be Orchestration-only?

# Familiar tools

## Services / SaaS
- [x] CicleCI - https://circleci.com/
    currently [in use](https://circleci.com/gh/bcgov/cas-ggircs) and exceedingly happy with speed and container support
- [x] Travis - https://travis-ci.org/
    a bit slow, but free is a good price
- [ ] CodeFresh - https://codefresh.io/

## Tools
- [ ] Drone - https://drone.io
- [ ] XL Release/Deploy - https://xebialabs.com/products/xl-release/
- [ ] GitHub Actions - https://github.com/features/actions
- [x] Jenkins - https://jenkins.io/
    was used for the entire build of Deis ([now AKS](https://azure.microsoft.com/en-us/services/kubernetes-service/)) and resulted in frequent false failures due to resource management issues (project-specific; not something I'd expect to encounter again per-se)
- [ ] JenkinsX - https://jenkins-x.io/
- [x] TeamCity - https://www.jetbrains.com/teamcity/
    as happy with this as with Circle but not currently in use on CAS project
- [ ] Knative - https://knative.dev/
- [ ] Kubernetes Prow - https://github.com/kubernetes/test-infra/tree/master/prow
- [ ] Huggin - https://github.com/huginn/huginn
- [ ] Kapitan - https://kapitan.dev/
- [ ] Brigade - https://brigade.sh/
- [x] GitLab - https://about.gitlab.com/product/continuous-integration/
    Despite some PR problems with them losing data on their hosted platform, I've been crazy impressed by the community edition of this entire suite, particularly how well it runs on Kubernetes. It's easy to deploy and the integrated CI runs quickly, beautifully, and has killer container-integration. The local docker container registry is helpful as well (though I'm aware it would be a duplication of a service offered by OpenShift). We didn't use GitLab for CAS because of OpenShift configuration: direct ssh is necessary for a `git` server. We use `gpg` keyrings to sign our code and certificate-based auth. I'm aware that GitLab could be deployed using HTTPS-only endpoints, but there's a dev UX problem with that (retyping passowords in an already auth'd shell session is annoying), and a bunch of security problems (E2E https is required, not SSL edge-termination; pasting passwords from a password manager creates the chance of pasting in the wrong context and ending up in `.bash_history` or worse, unclear prompts between git remotes encourage password reuse on multiple remotes, if even possible multi-factor auth is handed off to an external service that can't be audited, etc.)

## Dashboard View
- [ ] https://cncf.ci/

**Comment by GeorgeWalker** [comment]
A big one is missing, https://azure.microsoft.com/en-ca/services/devops/

I used its previous form (VSTS) for many years.  It's now open source friendly.  A few BC Gov areas already use it too, I've built "bcgov" projects with it in the past.

Given that Microsoft has bought Github I expect they will be leveraging that to promote their CI/CD system.

There's also a new product from Microsoft called "App Center" but it is more suited towards mobile development, it reminds me of the Red Hat "Feed Henry" product.  Those two products also help with continuous delivery.

**Comment by cvarjao** [comment]
@wenzowski, @ll911 , We are mainly looking from the Pipeline orchestration/running tools. Hopefully a tool that it is flexible enough that you can inject/run anything else you need.

**Comment by ll911** [comment]
@cvarjao i did include orchestration/scheduler tools in my list.

**Comment by WadeBarnes** [comment]
@cvarjao, I've been investigating GitLab CI for the VON projects.  The badges off this repo will link you to the GitLab resources; https://github.com/WadeBarnes/indy-catalyst.  The "main" repo is in GitHub and integrated into GitLab using their GitHub integration.  We started looking at it since we're contributing entire projects to Sovrin and their migrating to GitLab CI rather then Jenkins.

There is also the potential of integrating with directly with OpenShift; appears promising.  Seen some examples of runners in OpenShift doing builds and deploys.  Early examples require DID (so elevated permissions), but I think we could do the same thing with a runner using buildah, etc.  Something I still need to try out.

**Comment by stephenhillier** [comment]
I'm interested in the CI/CD products that run steps as containers by default, and I've experimented with both Github Actions and Brigade and had a good experience using both. 

The container for each step concept makes it easy to run either custom pipeline steps or tools/helpers from the community (e.g. https://cloud.google.com/cloud-build/docs/cloud-builders).  Here is an example of one I already made: 

https://github.com/stephenhillier/github-deployment

**Comment by ll911** [comment]
Anyone looked into atlas, terraforming and packer from hashicorp as cicd tool chain?

**Comment by stewartshea** [comment]
Atlas isn't a thing anymore AFAIK. I am a big TF user and we have leveraged
packer in the right use cases but ultimately these often solve different
challenges than releasing components into OpenShift of that's the primary
focus. True that there are k8s providers, but we prefer not to leverage
those since they need to confirm to HCL, and instead we often use the helm
provider which again isn't something we currently support in OpenShift.
That said, when orchestrating infrastructure outside of OpenShift, or where
ready built providers exist, TF can be super great. We are likely going to
leverage it in a few areas for detailed provisioning workflows in the
future.

**Comment by jleach** [comment]
@cvarjao I tested CircleCI with an macOS build (for iOS). Works great. So it gets my vote.
